In [86]:
import pandas  as pd

##### 1. 주민등록인구및세대현황.csv 가지고 와서 데이터 프레임으로 작성합니다.

In [87]:
data = pd.read_csv("주민등록인구및세대현황.csv",encoding='cp949')

In [88]:
data

,행정구역,2020년06월_총인구수,2020년06월_세대수,2020년06월_세대당 인구,2020년06월_남자 인구수,2020년06월_여자 인구수,2020년06월_남여 비율
0,서울특별시 (1100000000),"9,720,846","4,384,076",2.22,"4,732,275","4,988,571",0.95
1,서울특별시 종로구 (1111000000),"150,383","74,497",2.02,"73,288","77,095",0.95
2,서울특별시 종로구 청운효자동(1111051500),"12,609","5,395",2.34,"5,885","6,724",0.88
3,서울특별시 종로구 사직동(1111053000),"9,506","4,717",2.02,"4,281","5,225",0.82
4,서울특별시 종로구 삼청동(1111054000),"2,707","1,370",1.98,"1,301","1,406",0.93
...,...,...,...,...,...,...,...
3818,제주특별자치도 서귀포시 서홍동(5013058000),"10,416","4,259",2.45,"5,160","5,256",0.98
3819,제주특별자치도 서귀포시 대륜동(5013059000),"14,514","6,342",2.29,"7,359","7,155",1.03
3820,제주특별자치도 서귀포시 대천동(5013060000),"13,820","6,258",2.21,"7,011","6,809",1.03
3821,제주특별자치도 서귀포시 중문동(5013061000),"11,515","5,439",2.12,"5,926","5,589",1.06
3822,제주특별자치도 서귀포시 예래동(5013062000),"3,935","1,950",2.02,"2,041","1,894",1.08

##### 2. 인구정보 데이터 프레임의 컬럼명을 행정구역, 총인구수, 세대수, 세대당인구, 남자, 여자, 남녀비율 로 변경하세요

In [89]:
data=data.rename(columns = {'2020년06월_총인구수':'총인구수', '2020년06월_세대수':'세대수', '2020년06월_세대당 인구':'세대당인구','2020년06월_남자 인구수': '남자', '2020년06월_여자 인구수':'여자', '2020년06월_남여 비율':'남여비율'})

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3823 entries, 0 to 3822
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    3823 non-null   object
 1   총인구수    3823 non-null   object
 2   세대수     3823 non-null   object
 3   세대당인구   3823 non-null   float64
 4   남자      3823 non-null   object
 5   여자      3823 non-null   object
 6   남여비율    3823 non-null   float64
dtypes: float64(2), object(5)
memory usage: 209.2+ KB

In [91]:
data.columns

Index(['행정구역', '총인구수', '세대수', '세대당인구', '남자', '여자', '남여비율'], dtype='object')

##### 3. 남녀비율 컬럼을 제거합니다.

In [92]:
data.drop('남여비율',axis=1, inplace=True)

In [93]:
data.columns

Index(['행정구역', '총인구수', '세대수', '세대당인구', '남자', '여자'], dtype='object')

##### 4. 행정구역 컬럼의 ‘(’ ‘)’를 제거하고 시,구,동 컬럼을 만들어 분리해 넣고 대구지역의 값만 가지고 와서 인덱스를 새로 부여합니다.

In [94]:
data.행정구역=data.행정구역.str.split('(').str.get(0)

In [95]:
data['시'] = data['행정구역'].str.split().str.get(0)

In [96]:
data['구'] = data['행정구역'].str.split().str.get(1)

In [97]:
data['동'] = data['행정구역'].str.split().str.get(2)

In [98]:
data = data[data['시']=='대구광역시']

In [99]:
data.reset_index()

,index,행정구역,총인구수,세대수,세대당인구,남자,여자,시,구,동
0,673,대구광역시,"2,427,954","1,046,585",2.32,"1,198,815","1,229,139",대구광역시,NaN,NaN
1,674,대구광역시 중구,"76,984","38,954",1.98,"37,036","39,948",대구광역시,중구,NaN
2,675,대구광역시 중구 동인동,"8,755","5,183",1.69,"4,341","4,414",대구광역시,중구,동인동
3,676,대구광역시 중구 삼덕동,"6,733","4,018",1.68,"3,186","3,547",대구광역시,중구,삼덕동
4,677,대구광역시 중구 성내1동,"5,033","3,349",1.50,"2,394","2,639",대구광역시,중구,성내1동
...,...,...,...,...,...,...,...,...,...,...
145,818,대구광역시 달성군 옥포읍,"25,236","10,907",2.31,"12,774","12,462",대구광역시,달성군,옥포읍
146,819,대구광역시 달성군 현풍읍,"23,509","11,775",2.00,"12,263","11,246",대구광역시,달성군,현풍읍
147,820,대구광역시 달성군 가창면,"8,041","3,754",2.14,"4,004","4,037",대구광역시,달성군,가창면
148,821,대구광역시 달성군 하빈면,"3,725","2,025",1.84,"2,014","1,711",대구광역시,달성군,하빈면
149,822,대구광역시 달성군 구지면,"9,514","4,775",1.99,"5,104","4,410",대구광역시,달성군,구지면

##### 5. 총인구수, 남자, 여자 컬럼의 데이타 타입을 정수형으로 변경합니다.

In [100]:
data['총인구수']=data['총인구수'].str.replace(',','').astype('int')

In [101]:
data['남자']=data['남자'].str.replace(',','').astype('int')

In [102]:
data['여자']=data['여자'].str.replace(',','').astype('int')

In [103]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 673 to 822
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    150 non-null    object
 1   총인구수    150 non-null    int32
 2   세대수     150 non-null    object
 3   세대당인구   150 non-null    float64
 4   남자      150 non-null    int32
 5   여자      150 non-null    int32
 6   시       150 non-null    object
 7   구       149 non-null    object
 8   동       141 non-null    object
dtypes: float64(1), int32(3), object(5)
memory usage: 10.0+ KB

##### 6. 동별로 대구 인구를 차트로 표시합니다.

In [104]:
import matplotlib.pyplot as plt

              행정구역   총인구수     세대수  세대당인구     남자     여자      시    구     동
675   대구광역시 중구 동인동   8755   5,183   1.69   4341   4414  대구광역시   중구   동인동
676   대구광역시 중구 삼덕동   6733   4,018   1.68   3186   3547  대구광역시   중구   삼덕동
677  대구광역시 중구 성내1동   5033   3,349   1.50   2394   2639  대구광역시   중구  성내1동
678  대구광역시 중구 성내2동   4604   2,902   1.59   2328   2276  대구광역시   중구  성내2동
679  대구광역시 중구 성내3동   5218   2,565   2.03   2611   2607  대구광역시   중구  성내3동
..             ...    ...     ...    ...    ...    ...    ...  ...   ...
818  대구광역시 달성군 옥포읍  25236  10,907   2.31  12774  12462  대구광역시  달성군   옥포읍
819  대구광역시 달성군 현풍읍  23509  11,775   2.00  12263  11246  대구광역시  달성군   현풍읍
820  대구광역시 달성군 가창면   8041   3,754   2.14   4004   4037  대구광역시  달성군   가창면
821  대구광역시 달성군 하빈면   3725   2,025   1.84   2014   1711  대구광역시  달성군   하빈면
822  대구광역시 달성군 구지면   9514   4,775   1.99   5104   4410  대구광역시  달성군   구지면

[141 rows x 9 columns]

In [105]:
data

,행정구역,총인구수,세대수,세대당인구,남자,여자,시,구,동
673,대구광역시,2427954,"1,046,585",2.32,1198815,1229139,대구광역시,NaN,NaN
674,대구광역시 중구,76984,"38,954",1.98,37036,39948,대구광역시,중구,NaN
675,대구광역시 중구 동인동,8755,"5,183",1.69,4341,4414,대구광역시,중구,동인동
676,대구광역시 중구 삼덕동,6733,"4,018",1.68,3186,3547,대구광역시,중구,삼덕동
677,대구광역시 중구 성내1동,5033,"3,349",1.50,2394,2639,대구광역시,중구,성내1동
...,...,...,...,...,...,...,...,...,...
818,대구광역시 달성군 옥포읍,25236,"10,907",2.31,12774,12462,대구광역시,달성군,옥포읍
819,대구광역시 달성군 현풍읍,23509,"11,775",2.00,12263,11246,대구광역시,달성군,현풍읍
820,대구광역시 달성군 가창면,8041,"3,754",2.14,4004,4037,대구광역시,달성군,가창면
821,대구광역시 달성군 하빈면,3725,"2,025",1.84,2014,1711,대구광역시,달성군,하빈면
822,대구광역시 달성군 구지면,9514,"4,775",1.99,5104,4410,대구광역시,달성군,구지면

##### 7. 동별 남,여 인구를 차트로 표시합니다.

##### 8. Choropleth, geojson 등을 이용하여 동별 인구수를 색상별로 지도에 나타내시오